[package]
name = "celaut"
version = "0.1.0"
authors = ["Nathaniel Knight <nknight@cfenet.ubc.ca>"]
edition = "2018"

[dependencies]
image = "*"
rand = "*"
serde = { version = "1.0" }
serde_derive = "1.0"
serde_json = "1.0"